### ISSUE TITLE
请问有没有计划添加每日新闻热点推送🤣

### ISSUE THREAD

**Issue by Monicagege** [imxieyi/sticker_time_bot#7]
如题
其实我还有一个建议，可以单独设置起床晚安报时，有人觉得每个小时发一次就很烦，但是stop的话就没有早晚报时了

**Comment by imxieyi** [comment]
这个bot长期处于无人看管状态，搞什么新闻之类的完全没意义。

确实可以考虑支持指定报时的时间。

**Comment by imxieyi** [comment]
已经支持指定报时时间，你可以用`/addhour`添加需要报时的时间。
