### ISSUE TITLE
为什么机器人发不出消息啊

### ISSUE THREAD

**Issue by TiaraBasori** [imxieyi/sticker_time_bot#9]
把机器人拉进群组后根据readme设置一通但timebot就是不发送消息
timebot显示不可读取群组消息
请问是这个的问题吗，如果是又怎么解决呢
顺带一提大佬的waifu2xApp很好用

**Comment by imxieyi** [comment]
这个bot不需要读取群组消息，是不是api token设置有问题？私聊可以用吗？

**Comment by TiaraBasori** [comment]
私聊也不行啊

**Comment by imxieyi** [comment]
能发一下log吗？

**Comment by imxieyi** [comment]
你用的是[t.me/sticker_time_bot](http://t.me/sticker_time_bot)吗？这个bot连续运行时间太长了（超过1年）似乎出了点问题，重启了一下就好了。

**Comment by TiaraBasori** [comment]
啊大佬我自己的bot都搭好了这个bot恢复了？？
不过还是谢谢了

**Comment by imxieyi** [comment]
理论上并没有完全坏，发送sticker一直都是正常的，只是bot不知道为啥连续运行太久就收不到任何消息了。现在加了定时重启应该不会出同样的问题了。
